name: Trigger Firebase Release

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Node.js CI"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Run Script
        shell: bash
        run: echo "Hello World!"
      
