name: Trigger Firebase Release

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Node.js CI"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: echo '${{ GITHUB_EVENT_NAME }}' 
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: micahmeadows/sender-firebase
          event-type: deploy-firebase      
